name: NPM CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [8.x, 10.x , 12.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Build  
      uses: actions/checkout@v1
      with:
        submodules: true
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
      run: npm install --build-from-source
    - name: Upload binaries to GitHub Releases
      run: ./node_modules/.bin/node-pre-gyp package
      run: ./node_modules/.bin/node-pre-gyp-github publish --release
    

  publish:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM 
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NAPI_CLIP_NPM_TOKEN }}
      
