name: NPM CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build  
      run: npm install --build-from-source
    - name: Upload binaries to GitHub Releases
      run: npm run prebuild ${{ secrets.NAPI_CLIP_GITHUB_TOKEN }}

  publish:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: MeilCli/npm-update-check-action@v2
        id: outdated
        with:
          depth: 1
      - run: echo ${{ steps.outdated.outputs.npm_update_text }}
      - name: Publish to NPM
        if: steps.outdated.outputs.has_npm_update != 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NAPI_CLIP_NPM_TOKEN }}
      
