name: NPM CI

on: [push]

jobs:
  test-for-new-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - run: echo ::set-env name=new_version::$(git show $(git log --pretty=format:'%H' -2 | sed '1q;d'):./package.json | grep "\"version\"")
    - run: echo "$new_version"
    - run: echo ::set-env name=old_version::$(git show $(git log --pretty=format:'%H' -2 | sed '2q;d'):./package.json | grep "\"version\"")
    - run: echo "$old_version"
    - run: equals=$(if [ "$new_version" == "$old_version" ]; then echo "true"; else echo "false"; fi)
    - run: echo "$equals"
    - name: New Version?
      run: echo "::set-output name=output::${equals}"
      id: new_version
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Test
      if: steps.new_version.outputs.output
      run: echo "success"
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build
      run: npm install --build-from-source
    - name: Test
      run: xvfb-run ./node_modules/.bin/jest
      if: matrix.os == 'ubuntu-latest'
    - name: Test
      run: ./node_modules/.bin/jest
      if: matrix.os != 'ubuntu-latest'
    - name: Upload binaries to GitHub Releases
      run: npm run prebuild --upload--all ${{ secrets.NAPI_CLIP_GITHUB_TOKEN }}

  publish:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM
        if: 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NAPI_CLIP_NPM_TOKEN }}
      
