name: NPM CI

on: [push]

jobs:
  test-for-new-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - run: last=$(git log --pretty=format:'%H' -2 | sed '1q;d')
    - run: prelast=$(git log --pretty=format:'%H' -2 | sed '2q;d')
    - name: echo
      run: echo "xd"
      id: echo
    - name: Dump steps context
      env:
        STEPS_CONTEXT: haha
      run: echo ${{ toJson(env) }}

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build
      run: npm install --build-from-source
    - name: Test
      run: xvfb-run ./node_modules/.bin/jest
      if: matrix.os == 'ubuntu-latest'
    - name: Test
      run: ./node_modules/.bin/jest
      if: matrix.os != 'ubuntu-latest'
    - name: Upload binaries to GitHub Releases
      run: npm run prebuild --upload--all ${{ secrets.NAPI_CLIP_GITHUB_TOKEN }}

  publish:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM
        if: 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NAPI_CLIP_NPM_TOKEN }}
      
